env:
        TERM: alacritty

window:
        dimensions:
                columns: 84
                lines: 24
        # window with title bars
        decorations: full
        title: (´▽｀)

font:
        normal:
                #family: PragmataPro
                family: Monaco
        bold:
                #family: PragmataPro
                family: Monaco
        size: 15.0

# key bindings
# these key_bindings are for using emacs in alacritty
# see https://blog.risouf.net/entry/2019-05-13-use-emacs-on-alacritty.html
key_bindings:
        - { key: Space, mods: Alt, action: ToggleViMode }
        - { key: A,         mods: Alt,       chars: "\x1ba"                       }
        - { key: B,         mods: Alt,       chars: "\x1bb"                       }
        - { key: C,         mods: Alt,       chars: "\x1bc"                       }
        - { key: D,         mods: Alt,       chars: "\x1bd" }
        - { key: E,         mods: Alt,       chars: "\x1be" }
        - { key: F,         mods: Alt,       chars: "\x1bf" }
        - { key: G,         mods: Alt,       chars: "\x1bg" }
        - { key: H,         mods: Alt,       chars: "\x1bh" }
        - { key: I,         mods: Alt,       chars: "\x1bi" }
        - { key: J,         mods: Alt,       chars: "\x1bj" }
        - { key: K,         mods: Alt,       chars: "\x1bk" }
        - { key: L,         mods: Alt,       chars: "\x1bl" }
        - { key: M,         mods: Alt,       chars: "\x1bm" }
        - { key: N,         mods: Alt,       chars: "\x1bn" }
        - { key: O,         mods: Alt,       chars: "\x1bo" }
        - { key: P,         mods: Alt,       chars: "\x1bp" }
        - { key: Q,         mods: Alt,       chars: "\x1bq" }
        - { key: R,         mods: Alt,       chars: "\x1br" }
        - { key: S,         mods: Alt,       chars: "\x1bs" }
        - { key: T,         mods: Alt,       chars: "\x1bt" }
        - { key: U,         mods: Alt,       chars: "\x1bu" }
        - { key: V,         mods: Alt,       chars: "\x1bv" }
        - { key: W,         mods: Alt,       chars: "\x1bw" }
        - { key: X,         mods: Alt,       chars: "\x1bx" }
        - { key: Y,         mods: Alt,       chars: "\x1by" }
        - { key: Z,         mods: Alt,       chars: "\x1bz" }
        - { key: A,         mods: Alt|Shift, chars: "\x1bA" }
        - { key: B,         mods: Alt|Shift, chars: "\x1bB" }
        - { key: C,         mods: Alt|Shift, chars: "\x1bC" }
        - { key: D,         mods: Alt|Shift, chars: "\x1bD" }
        - { key: E,         mods: Alt|Shift, chars: "\x1bE" }
        - { key: F,         mods: Alt|Shift, chars: "\x1bF" }
        - { key: G,         mods: Alt|Shift, chars: "\x1bG" }
        - { key: H,         mods: Alt|Shift, chars: "\x1bH" }
        - { key: I,         mods: Alt|Shift, chars: "\x1bI" }
        - { key: J,         mods: Alt|Shift, chars: "\x1bJ" }
        - { key: K,         mods: Alt|Shift, chars: "\x1bK" }
        - { key: L,         mods: Alt|Shift, chars: "\x1bL" }
        - { key: M,         mods: Alt|Shift, chars: "\x1bM" }
        - { key: N,         mods: Alt|Shift, chars: "\x1bN" }
        - { key: O,         mods: Alt|Shift, chars: "\x1bO" }
        - { key: P,         mods: Alt|Shift, chars: "\x1bP" }
        - { key: Q,         mods: Alt|Shift, chars: "\x1bQ" }
        - { key: R,         mods: Alt|Shift, chars: "\x1bR" }
        - { key: S,         mods: Alt|Shift, chars: "\x1bS" }
        - { key: T,         mods: Alt|Shift, chars: "\x1bT" }
        - { key: U,         mods: Alt|Shift, chars: "\x1bU" }
        - { key: V,         mods: Alt|Shift, chars: "\x1bV" }
        - { key: W,         mods: Alt|Shift, chars: "\x1bW" }
        - { key: X,         mods: Alt|Shift, chars: "\x1bX" }
        - { key: Y,         mods: Alt|Shift, chars: "\x1bY" }
        - { key: Z,         mods: Alt|Shift, chars: "\x1bZ" }
        - { key: Key1,      mods: Alt,       chars: "\x1b1" }
        - { key: Key2,      mods: Alt,       chars: "\x1b2" }
        - { key: Key3,      mods: Alt,       chars: "\x1b3" }
        - { key: Key4,      mods: Alt,       chars: "\x1b4" }
        - { key: Key5,      mods: Alt,       chars: "\x1b5" }
        - { key: Key6,      mods: Alt,       chars: "\x1b6" }
        - { key: Key7,      mods: Alt,       chars: "\x1b7" }
        - { key: Key8,      mods: Alt,       chars: "\x1b8" }
        - { key: Key9,      mods: Alt,       chars: "\x1b9" }
        - { key: Key0,      mods: Alt,       chars: "\x1b0" }
        - { key: Grave,     mods: Alt,       chars: "\x1b`" }
        - { key: Grave,     mods: Alt|Shift, chars: "\x1b~" }
        - { key: Period,    mods: Alt,       chars: "\x1b." }
        - { key: Key8,      mods: Alt|Shift, chars: "\x1b*" }
        - { key: Key3,      mods: Alt|Shift, chars: "\x1b#" }
        - { key: Period,    mods: Alt|Shift, chars: "\x1b>" }
        - { key: Comma,     mods: Alt|Shift, chars: "\x1b<" }
        - { key: Minus,     mods: Alt|Shift, chars: "\x1b_" }
        - { key: Key5,      mods: Alt|Shift, chars: "\x1b%" }
        - { key: Key6,      mods: Alt|Shift, chars: "\x1b^" }
        - { key: Backslash, mods: Alt,       chars: "\x1b\\"}
        - { key: Backslash, mods: Alt|Shift, chars: "\x1b|" }

## Colors (quantum)
#colors:
        ## Default colors
        #primary:
                #background: '#253237'
                #foreground: '#A4B2BC'

        ## Normal colors
        #normal:
                #black: '#01060E'
                #red: '#D76F83'
                #green: '#88BA7E'
                #yellow: '#D5B779'
                #blue: '#72ADE2'
                #magenta: '#DD7186'
                #cyan: '#6DC5CD'
                #white: '#A4B1BC'

        ## Bright colors
        #bright:
                #black: '#01060E'
                #red: '#D76F83'
                #green: '#88BA7E'
                #yellow: '#D5B779'
                #blue: '#72ADE2'
                #magenta: '#DD7186'
                #cyan: '#6DC5CD'
                #white: '#A4B1BC'

## colors (arcadia)
#colors:
        ## Default colors
        #primary:
                #background: '#3C3C3C'
                #foreground: '#DEDEDE'

        ## Normal colors
        #normal:
                #black: '#262626'
                #red: '#AD005E'
                #green: '#067B7B'
                #yellow: '#E87D05'
                #blue: '#0087AF'
                #magenta: '#8787D7'
                #cyan: '#5E86AD'
                #white: '#DEDEDE'

        ## Bright colors
        #bright:
                #black: '#262626'
                #red: '#AD005E'
                #green: '#067B7B'
                #yellow: '#E87D05'
                #blue: '#0087AF'
                #magenta: '#8787D7'
                #cyan: '#5E86AD'
                #white: '#DEDEDE'

## colors (simple-dark)
#colors:
        ## Default colors
        #primary:
                #background: '#101010'
                #foreground: '#BCBCBC'

        ## Normal colors
        #normal:
                #black: '#252525'
                #red: '#FF0000'
                #green: '#8A8A8A'
                #yellow: '#8A8A8A'
                #blue: '#585858'
                #magenta: '#8A8A8A'
                #cyan: '#8A8A8A'
                #white: '#BCBCBC'

        ## Bright colors
        #bright:
                #black: '#252525'
                #red: '#FF0000'
                #green: '#8A8A8A'
                #yellow: '#8A8A8A'
                #blue: '#585858'
                #magenta: '#8A8A8A'
                #cyan: '#8A8A8A'
                #white: '#BCBCBC'

## Colors (tomorrow)
colors:
        # Default colors
        primary:
                background: '#303030'
                foreground: '#969896'

        # Normal colors
        normal:
                black: '#01060E'
                red: '#CC6666'
                green: '#B5BD68'
                yellow: '#FFFF00'
                blue: '#81A2BE'
                magenta: '#DD7186'
                cyan: '#6DC5CD'
                white: '#A4B1BC'

        # Bright colors
        bright:
                black: '#01060E'
                red: '#CC6666'
                green: '#B5BD68'
                yellow: '#FFFF00'
                blue: '#81A2BE'
                magenta: '#DD7186'
                cyan: '#6DC5CD'
                white: '#A4B1BC'

